modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
issueTrackerURL="https://github.com/The-Acronym-Coders/Vex-s-Brilliant-Machines/issues"
[[mods]] #mandatory
modId="vexsbm" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Vex's Brilliant Machines" #mandatory
authors="Vex, Lanse505" #optional
description='''

'''

[[dependencies.vexsbm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.vexsbm]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31.2.20,)" #mandatory
    ordering="AFTER"
    side="BOTH"

[[dependencies.vexsbm]]
    modId="titanium" #mandatory
    mandatory=true #mandatory
    versionRange="[2.4,)" #mandatory
    ordering="AFTER"
    side="BOTH"

